name: Linter

on:
  workflow_call:
    inputs:
      flake8:
        required: false
        default: true
        type: boolean
      folder:
        required: false
        default: "botcity"
        type: string
      mypy:
        required: false
        default: false
        type: boolean
      list_os:
        type: string
        required: false
        default: "['ubuntu-latest']"
      list_version:
        type: string
        required: false
        default: "['3.7']"


jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
        run:
          shell: bash

    strategy:
      matrix:
        os:  ${{fromJson(inputs.list_os)}}
        python-version:  ${{fromJson(inputs.list_version)}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linter Dependencies
        run: |
          pip install flake8 mypy types-requests

      - name: Run Flake8 Linter
        if: ${{ inputs.flake8 }}
        run: |
          flake8 ${{ inputs.folder }}

      - name: Run mypy Linter
        if: ${{ inputs.mypy }}
        run: |
          mypy --namespace-packages -p ${{ inputs.folder }}
