name: Linter

on:
  workflow_call:
    inputs:
      flake8:
        required: false
        default: true
        type: boolean
      mypy:
        required: false
        default: false
        type: boolean
      os:
        required: false
        default: "[ubuntu-latest]"
      version:
        type: string
        required: false
        default: "[3.7]"


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.setVariables.outputs.os }}
      version: ${{ steps.setVariables.outputs.version }}
    steps:
      - id: Set variable os
        run: |
          echo "::set-output name=os::os"
        env:
          os: ${{ inputs.os }}
      - id: Set variable version
        run: |
          echo "::set-output name=version::version"
        env:
          version: ${{ inputs.version }}


  build:
    runs-on: ${{ matrix.os }}

    needs: setup
    permissions:
      security-events: write

    defaults:
        run:
          shell: bash

    strategy:
      matrix:
        os:  ${{ fromJson(needs.setup.outputs.os) }}
        python-version:  ${{ fromJson(needs.setup.outputs.version) }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linter Dependencies
        run: |
          pip install flake8 mypy types-requests

      - name: Run Flake8 Linter
        if: ${{ inputs.flake8 }}
        run: |
          flake8 botcity

      - name: Run mypy Linter
        if: ${{ inputs.mypy }}
        run: |
          mypy --namespace-packages -p "botcity"
