name: Linter

on:
  workflow_call:
    inputs:
      flake8:
        required: false
        default: true
        type: boolean
      mypy:
        required: false
        default: false
        type: boolean
      os:
        required: false
        default: ubuntu-latest
        type: string


jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
        run:
          shell: bash

    strategy:
      matrix:
        fail-fast: false
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linter Dependencies
        run: |
          pip install flake8 mypy types-requests

      - name: Run Flake8 Linter
        if: ${{ inputs.flake8 }}
        run: |
          flake8 botcity

      - name: Run mypy Linter
        if: ${{ inputs.mypy }}
        run: |
          mypy --namespace-packages -p "botcity"
