name: Publish Python distributions to PyPI

on:
  workflow_call:
    inputs:
      version_python:
        required: false
        type: string
        default: 3.9
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python ${{ inputs.version_python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.version_python }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}