name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      commands:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_INSTANCE_ID:
        required: true
      ENV_VARS:
        required: true

jobs:
  deploy:
    name: Generic Deploy via SSM
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Set environment variables from .env
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env
          set -a
          source .env
          set +a

      - name: Create script with injected commands
        run: |
          echo '${{ inputs.commands }}' > ./deploy-ssm.sh
          chmod +x ./deploy-ssm.sh

      - name: Execute script via SSM
        run: |
          .github/scripts/run-ssm-command.sh \
            --instance-id ${{ inputs.ec2-instance-id }} \
            --region ${{ secrets.EC2_INSTANCE_ID }} \
            --script-path ./deploy-ssm.sh
